package com.wisdom.company.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;

import com.wisdom.common.model.Company;
import com.wisdom.common.model.SheetBalance;
import com.wisdom.common.model.SheetCash;

public class SheetBalanceMapper implements RowMapper<SheetBalance> {
	public SheetBalance mapRow(ResultSet rs, int index) throws SQLException {
		SheetBalance u = new SheetBalance(
				rs.getLong("id"),
				rs.getLong("company_id"),
				rs.getString("expiry_date"),
				rs.getString("preparedby"),
				rs.getString("company_controller"),
				rs.getString("finance_chief"),
				rs.getString("tabulator"),
				rs.getDouble("monetary_resources_ending_balance"),
				rs.getDouble("monetary_resources_beginning_balance"),
				rs.getDouble("short_term_investments_ending_balance"),
				rs.getDouble("short_term_investments_beginning_balance"),
				rs.getDouble("bill_receivable_ending_balance"),
				rs.getDouble("bill_receivable_beginning_balance"),
				rs.getDouble("accounts_receivable_ending_balance"),
				rs.getDouble("accounts_receivable_beginning_balance"),
				rs.getDouble("prepayment_ending_balance"),
				rs.getDouble("prepayment_beginning_balance"),
				rs.getDouble("dividends_receivable_ending_balance"),
				rs.getDouble("dividends_receivable_beginning_balance"),
				rs.getDouble("interest_receivable_ending_balance"),
				rs.getDouble("interest_receivable_beginning_balance"),
				rs.getDouble("other_receivables_ending_balance"),
				rs.getDouble("other_receivables_beginning_balance"),
				rs.getDouble("stock_ending_balance"),
				rs.getDouble("stock_beginning_balance"),
				rs.getDouble("stock_raw_materials_ending_balance"),
				rs.getDouble("stock_raw_materials_beginning_balance"),
				rs.getDouble("stock_product_ending_balance"),
				rs.getDouble("stock_product_beginning_balance"),
				rs.getDouble("stock_merchandise_inventory_ending_balance"),
				rs.getDouble("stock_merchandise_inventory_beginning_balance"),
				rs.getDouble("stock_revolving_materials_ending_balance"),
				rs.getDouble("stock_revolving_materials_beginning_balance"),
				rs.getDouble("other_current_assets_ending_balance"),
				rs.getDouble("other_current_assets_beginning_balance"),
				rs.getDouble("total_current_assets_ending_balance"),
				rs.getDouble("total_current_assets_beginning_balance"),
				rs.getDouble("long_term_investments_in_bonds_ending_balance"),
				rs.getDouble("long_term_investments_in_bonds_beginning_balance"),
				rs.getDouble("long_term_investment_on_stocks_ending_balance"),
				rs.getDouble("long_term_investment_on_stocks_beginning_balance"),
				rs.getDouble("fixed_assets_original_cost_ending_balance"),
				rs.getDouble("fixed_assets_original_cost_beginning_balance"),
				rs.getDouble("accumulated_depreciation_ending_balance"),
				rs.getDouble("accumulated_depreciation_beginning_balance"),
				rs.getDouble("book_value_of_fixed_assets_ending_balance"),
				rs.getDouble("book_value_of_fixed_assets_beginning_balance"),
				rs.getDouble("construction_in_process_ending_balance"),
				rs.getDouble("construction_in_process_beginning_balance"),
				rs.getDouble("construction_materials_ending_balance"),
				rs.getDouble("construction_materials_beginning_balance"),
				rs.getDouble("removal_of_fixed_assets_ending_balance"),
				rs.getDouble("removal_of_fixed_assets_beginning_balance"),
				rs.getDouble("biological_assets_ending_balance"),
				rs.getDouble("biological_assets_beginning_balance"),
				rs.getDouble("intangible_assets_ending_balance"),
				rs.getDouble("intangible_assets_beginning_balance"),
				rs.getDouble("development_expenditure_ending_balance"),
				rs.getDouble("development_expenditure_beginning_balance"),
				rs.getDouble("long_term_prepaid_expenses_ending_balance"),
				rs.getDouble("long_term_prepaid_expenses_beginning_balance"),
				rs.getDouble("other_non_current_assets_ending_balance"),
				rs.getDouble("other_non_current_assets_beginning_balance"),
				rs.getDouble("total_non_current_assets_ending_balance"),
				rs.getDouble("total_non_current_assets_beginning_balance"),
				rs.getDouble("total_assets_ending_balance"),
				rs.getDouble("total_assets_beginning_balance"),
				rs.getDouble("short_loan_ending_balance"),
				rs.getDouble("short_loan_beginning_balance"),
				rs.getDouble("notes_payable_ending_balance"),
				rs.getDouble("notes_payable_beginning_balance"),
				rs.getDouble("payable_account_ending_balance"),
				rs.getDouble("payable_account_beginning_balance"),
				rs.getDouble("deposit_received_ending_balance"),
				rs.getDouble("deposit_received_beginning_balance"),
				rs.getDouble("employee_benefits_payable_ending_balance"),
				rs.getDouble("employee_benefits_payable_beginning_balance"),
				rs.getDouble("taxes_payable_ending_balance"),
				rs.getDouble("taxes_payable_beginning_balance"),
				rs.getDouble("interest_payable_ending_balance"),
				rs.getDouble("interest_payable_beginning_balance"),
				rs.getDouble("profit_payable_ending_balance"),
				rs.getDouble("profit_payable_beginning_balance"),
				rs.getDouble("accounts_payable_others_ending_balance"),
				rs.getDouble("accounts_payable_others_beginning_balance"),
				rs.getDouble("other_current_liabilities_ending_balance"),
				rs.getDouble("other_current_liabilities_beginning_balance"),
				rs.getDouble("total_current_liabilities_ending_balance"),
				rs.getDouble("total_current_liabilities_beginning_balance"),
				rs.getDouble("long_loan_ending_balance"),
				rs.getDouble("long_loan_beginning_balance"),
				rs.getDouble("long_term_payables_ending_balance"),
				rs.getDouble("long_term_payables_beginning_balance"),
				rs.getDouble("deferred_income_ending_balance"),
				rs.getDouble("deferred_income_beginning_balance"),
				rs.getDouble("other_non_current_liabilities_ending_balance"),
				rs.getDouble("other_non_current_liabilities_beginning_balance"),
				rs.getDouble("total_non_current_liabilities_ending_balance"),
				rs.getDouble("total_non_current_liabilities_beginning_balance"),
				rs.getDouble("total_liabilities_ending_balance"),
				rs.getDouble("total_liabilities_beginning_balance"),
				rs.getDouble("paid_in_capital_ending_balance"),
				rs.getDouble("paid_in_capital_beginning_balance"),
				rs.getDouble("capital_reserve_ending_balance"),
				rs.getDouble("capital_reserve_beginning_balance"),
				rs.getDouble("earned_surplus_ending_balance"),
				rs.getDouble("earned_surplus_beginning_balance"),
				rs.getDouble("undistributed_profit_ending_balance"),
				rs.getDouble("undistributed_profit_beginning_balance"),
				rs.getDouble("total_equities_ending_balance"),
				rs.getDouble("total_equities_beginning_balance"),
				rs.getDouble("total_liabilities_and_owner_equity_ending_balance"),
				rs.getDouble("total_liabilities_and_owner_equity_beginning_balance"),
				rs.getString("create_time"));
		return u;
	}
}